### ISSUE TITLE
如何解决：FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './projects/'

### ISSUE THREAD

**Issue by AaronDon2018** [DL-Practise/YoloX_EasyTrain#2]
我在启用插件的时候（运行python main_widget.py）遇到了这个问题：
```
(pytorch_gpu) F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain>python main_widget.py
Traceback (most recent call last):
  File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 228, in <module>
    cMainWidget = CMainWidget()
  File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 39, in __init__
    self.on_treeProj_init()
  File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 46, in on_treeProj_init
    for prj in os.listdir(root_dir):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './projects/'
```
我用的是windows系统，请问有人知道为什么出现了这种错误吗？

**Comment by ranchen421** [comment]
既然没有文件夹，那你自己创建一个不就可以了吗


在项目文件夹内创建一个名为projects的文件夹

**Comment by flyingfish7777** [comment]
> 我在启用插件的时候（运行python main_widget.py）遇到了这个问题：
> 
> ```
> (pytorch_gpu) F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain>python main_widget.py
> Traceback (most recent call last):
>   File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 228, in <module>
>     cMainWidget = CMainWidget()
>   File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 39, in __init__
>     self.on_treeProj_init()
>   File "F:\Users\TZF\Documents\GitHub\YoloX_EasyTrain\main_widget.py", line 46, in on_treeProj_init
>     for prj in os.listdir(root_dir):
> FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './projects/'
> ```
> 
> 我用的是windows系统，请问有人知道为什么出现了这种错误吗？

你好，我遇到了同样的问题，请问解决了吗
